name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: install xpretty
      run: gem install xcpretty
    - name: Test
      run: |
        xcodebuild -version
        xcodebuild -showsdks
        set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MapCache.xcworkspace -scheme MapCache-Example -sdk iphonesimulator13.4 ONLY_ACTIVE_ARCH=NO | xcpretty
        pod lib lint
